### ISSUE TITLE
关于T1、T2，以及开发集的获取

### ISSUE THREAD

**Issue by twjiang** [thunlp/IEAJKE#1]
每个数据集只有一个存储triple文件，请问如何获取文中所提到的T1、T2，以及大小为1000开发集？

**Comment by ProKil** [comment]
1. 为了方便程序处理，我们提供的数据是将T1，T2合在一起的triple文件。如果你很希望将T1，T2分开，那么你可以根据我们提供的entity2id.txt来判断，结尾有$的就是KG2的实体，否则为KG1的。
2. 开发集会很快提供。
