### ISSUE TITLE
提示错误：段错误 (核心已转储)

### ISSUE THREAD

**Issue by hatleon** [thunlp/IEAJKE#3]
（1）运行命令./transE，提示段错误 (核心已转储)。查了一下是内存问题，双系统用ubuntu测试你的代码，请问怎么解决，谢谢！

（2）运行Fast-TransX项目，运行指令报同样错误：./transE -size 50 -sizeR 50 -input ./data -output ./ -load LOAD ./data -load-binary 0 -out-binary 0 -thread 3 -epochs 5 -nbatches 10 -alpha ALPHA 0.01 -margin MARGIN 1 -note ./

**Comment by hatleon** [comment]
通过gdb调试，https://jingyan.baidu.com/article/acf728fd464984f8e410a369.html ，在IEAJKE-master目录下新建res空文件夹即可。

**Comment by ljd12345** [comment]
您好，请问您最后解决了“段错误”问题嘛？我不断调试+创建res文件夹，这个错误还是没有解决。请问您调试过程中修改了那些代码bug？

**Comment by hatleon** [comment]
> 您好，请问您最后解决了“段错误”问题嘛？我不断调试+创建res文件夹，这个错误还是没有解决。请问您调试过程中修改了那些代码bug？

时间久有点忘了，应该是相对路径的问题，还有就是缺失res文件夹。
string inPath = "../data/";
string outPath = "../res/";

你可以在IEAJKE-master目录下新建res空文件夹，进入src文件夹运行命令g++ transE.cpp -o transE -pthread -O3 -std=c++11 -march=native

**Comment by ljd12345** [comment]
好的，谢谢您！ 我再试试。

**Comment by ljd12345** [comment]
代码可以编译，但执行代码只能打印出一行结果“5000 known entities pairs.”，之后还是报“段错误”。可能存在其他问题但我没找到。

**Comment by hatleon** [comment]
> 代码可以编译，但执行代码只能打印出一行结果“5000 known entities pairs.”，之后还是报“段错误”。可能存在其他问题但我没找到。

你是在window11下的子系统ubuntu运行的吗？可以去虚拟机下的ubuntu或真实的linux系统试试。通过ps aux查看STAT的状态如果是S开头是sleep休眠状态。
