### ISSUE TITLE
关于common_entities

### ISSUE THREAD

**Issue by NerdTsai** [thunlp/IEAJKE#4]
该文件是不是已经包括了kg1和kg2的所有对齐实体对，是不是可以认为该文件以外的任意实体对不存在对齐关系

**Comment by NerdTsai** [comment]
并且，在common_entities.txt中绝大部分的kg2实体，在new_entity2id.txt中无法找到

**Comment by ProKil** [comment]
不是的，common entities是alignment seeds。对于alignment seeds 我们只分配了一个id。比如，common entities中的一条记录，xxx xxx$，表示xxx和xxx$是已知的对应关系。在new_entitiy2id.txt中，xxx id，表示的是xxx和xxx$都对应这个id。其他的xxx和xxx$均表示kg1和kg2之间的对齐关系。

**Comment by NerdTsai** [comment]
收到，感谢您的耐心解答

Hao Zhu <notifications@github.com> 于2019年7月12日周五 上午11:00写道：
